### ISSUE TITLE
Repo is excluded

### ISSUE THREAD

**Issue by InvisiblePro** [DhananjayPorwal/hacktoberfest2021#377]
You had Labelled as "HACKTOBERFEST-ACCEPTED" but it is showing as "EXCLUDE"

**Comment by InvisiblePro** [comment]
![image](https://user-images.githubusercontent.com/92221630/193454251-213faa73-fc12-4187-8895-8a5d189feda4.png)

**Comment by InvisiblePro** [comment]
or else should i do PR again, and plz accept it with the label, instead of just labelling.....

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.
